# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: (?x)(tests/|pixl/defaults.py|README.md|locales/)
      - id: end-of-file-fixer
        exclude: (?x)(tests/|pixl/defaults.py|README.md|locales/)
      - id: check-yaml
        exclude: (?x)(tests/|pixl/defaults.py|README.md|locales/)
      - id: debug-statements
        exclude: (?x)(tests/|pixl/defaults.py|README.md|locales/)
      - id: check-added-large-files
        exclude: (?x)(tests/|pixl/defaults.py|README.md|locales/)
      - id: requirements-txt-fixer
        exclude: (?x)(tests/|pixl/defaults.py|README.md|locales/)
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: (?x)(tests/|pixl/defaults.py|README.md|locales/)
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.246
    hooks:
      - id: ruff
        args: [--fix]
ci:
    autofix_commit_msg: ðŸŽ¨ [pre-commit.ci] Auto format from pre-commit.com hooks
    autoupdate_commit_msg: â¬† [pre-commit.ci] pre-commit autoupdate
